### ISSUE TITLE
IntranetUserJS: Transfers to receive patron info to checkmark

### ISSUE THREAD

**Issue by lmstrand** [KohaSuomi/koha-plugin-intranetjs-transferstoreceive-patron-info-checkmark#1]
Pluginin testaus/käyttöönotto:

Poista intranetUserJS-asetuksesta rimpsu Muuttaa vastaanotettavien kuljetusten varaustietokentän (transferstoreceive) muotoon kyllä/ei
Aktivoi plugin IntranetUserJS: Transfers to receive patron info to checkmark
Tarkista, ettei vastaanotettavat kuljetukset-raportilla näy asiakastietoja

**Comment by lmstrand** [comment]
Seuranta kimpoista, joissa plugin otettu käyttöön. Kommentoi tikettiä, kun muutos on tehty omaan kimppaan:

- [x] Lappi
- [x] OUTI
- [x] Siili
- [x] Vaara
- [x] Lumme
- [x] Kyyti
- [x] Helle
- [x] Kirkes
- [x] Lastu
- [x] Vaski

**Comment by Kati-Helle** [comment]
Helle-nextissä toimii.
Varattu asiakkaalle -sarake on arvoton, kun niteeseen ei ole varausta.
Varattu asiakkaalle -sarakkeessa on väkänen, kun niteeseen on varaus..
![kuva](https://github.com/user-attachments/assets/f8353d40-9cc8-4b57-a6fb-b02f1fb44d01)

**Comment by pknuuti** [comment]
Toimii Vaaran nextillä.

**Comment by ReettaSiili** [comment]
Toimii Siilin nextillä.

**Comment by lmstrand** [comment]
Kiitos testeistä.

**Comment by piiaseme** [comment]
Toimii myös OUTIn nextillä.

**Comment by LeenaKinnunen** [comment]
Otettu Lapissa käyttöön nextillä, toimii.

**Comment by ElinaUotila** [comment]
Otettu käyttöön Kirkesin nextillä.

**Comment by LastuJanneS** [comment]
Lastun nextillä myös otettu käyttöön.

**Comment by MikkoLiimatainen** [comment]
Otettu Vaskin Nextillä käyttöön.

Pieni lisäys tähän kaivattaisiin vielä. Kohtaan
```
return $(this).text() === "None" || $(this).text() === "Ei mitään";
``` 
tarvittaisiin myös käsittely ruotsille. Mennee tällä lisäyksellä:
```
$(this).text() === "Ingen"
```

**Comment by AnneliO** [comment]
> Otettu Vaskin Nextillä käyttöön.
> 
> Pieni lisäys tähän kaivattaisiin vielä. Kohtaan
> 
> ```
> return $(this).text() === "None" || $(this).text() === "Ei mitään";
> ```
> 
> tarvittaisiin myös käsittely ruotsille. Mennee tällä lisäyksellä:
> 
> ```
> $(this).text() === "Ingen"
> ```

Mitä tämä tekee?

**Comment by MikkoLiimatainen** [comment]
> > Otettu Vaskin Nextillä käyttöön.
> > Pieni lisäys tähän kaivattaisiin vielä. Kohtaan
> > ```
> > return $(this).text() === "None" || $(this).text() === "Ei mitään";
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > tarvittaisiin myös käsittely ruotsille. Mennee tällä lisäyksellä:
> > ```
> > $(this).text() === "Ingen"
> > ```
> 
> Mitä tämä tekee?

Nähdäkseni tuo pätkä etsii määritellyt tekstit varattu asiakkaalle -sarakkeesta, jotta ne voidaan tyhjentää, jos varausta ei ole. Ruotsinkielisessä versiossa tätä ei nyt tapahdu, koska tuo etsii vain englannin- ja suomenkielisiä tekstejä. Ruotsinkielisessä versiossa sarakkeen sisältö on Ingen, jos varausta ei ole, joten sisältö olisi syytä tarkastaa senkin varalta.

**Comment by AnneliO** [comment]
Kysäsin Kassulta tuosta ja ilmeisesti aiemmin ruotsiksi siinä luki myös "None". Olisikohan käännöstiedosto täydentynyt tuon osalta ja siksi se ei nyt enää täsmää tuon Nonen kanssa.

Eli jos Lari saat tuon vielä lisättyä, niin sitten varmaan hyvä. :)

**Comment by lmstrand** [comment]
Lisätään pluginiin.

**Comment by lmstrand** [comment]
Lisätty ruotsinkielisen termin tarkistus ja muutos viety nexteille.

**Comment by MikkoLiimatainen** [comment]
> Kysäsin Kassulta tuosta ja ilmeisesti aiemmin ruotsiksi siinä luki myös "None". Olisikohan käännöstiedosto täydentynyt tuon osalta ja siksi se ei nyt enää täsmää tuon Nonen kanssa.
> 
> Eli jos Lari saat tuon vielä lisättyä, niin sitten varmaan hyvä. :)

No, ihmettelinkin, että tuo puuttui. Nyt menee ruotsikin piiloon taas.

**Comment by AnneliO** [comment]
Testasin outi-nextillä ja siellä myös toimii ruotsinkielisessä oikein nyt.

**Comment by AnneliO** [comment]
Tämä on kaikilla kunnossa, joten suljen tiketin.
